### ISSUE TITLE
Private Keys inside executable

### ISSUE THREAD

**Issue by chmichael** [svanas/delphereum#10]
Hello,
  Isn't dangerous to store private keys into the executable that can be reversed engineered ?
  
  Thank you

**Comment by svanas** [comment]
We do not store private keys. Yes, they are potentially in memory but...

1. We keep them on the stack (not on the heap) where they are zero'ed out as soon as they go out of scope, and
2. Every crypto wallet will need to ask you for your private key (or seed phrase), and Delphereum-made apps aren't any different. As a matter of fact, most of them are wallets.

That being said, it would be awesome if this library would support [WalletConnect](https://github.com/walletconnect) technology. It is on our list of things to do.

**Comment by chmichael** [comment]
Thank you
