### ISSUE TITLE
Library issue.

### ISSUE THREAD

**Issue by khatripp** [svanas/delphereum#14]
How and where shall I can setup the path and on what IDE ? Is RAD studio -11 is suitable for that? 
![image](https://user-images.githubusercontent.com/91184559/142401203-ebcc77ec-c443-445a-a95e-905e426b2d56.png)
Please help as soon as possible.

**Comment by svanas** [comment]
1. add the path to [./DelphiBigNumbers/Source](url) to _Project > Options > Delphi Compiler > Search Path_
2. do the same for the @Xor-el's crypto libraries, or use [this app](https://github.com/UrbanCohortDev/CryptoLibManager).

**Comment by khatripp** [comment]
![image](https://user-images.githubusercontent.com/91184559/142478224-a92d22a1-fbe5-4b5a-9d6e-25499d34108d.png)
done the dependencies part. but these new 5 errors are there. can you please help me to resolve them?
