### ISSUE TITLE
E2003 Undeclared identifier: 'AsExtended' , F2063 Could not compile used unit 'web3.eth.erc20.pas'

### ISSUE THREAD

**Issue by khatripp** [svanas/delphereum#16]
![image](https://user-images.githubusercontent.com/91184559/143000228-b7605a1a-787f-4726-9f7f-0e2e1599cb15.png)
Hello sir, Please give a solution as soon as possible. Can you suggest me which compiler should I use? or This is library issue?

**Comment by svanas** [comment]
@rvelthuis has [excluded AsExtended from 64-bit Windows](https://github.com/rvelthuis/DelphiBigNumbers/blob/master/Source/Velthuis.BigIntegers.pas#L230-L232), that's why. Anyway, please re-pull from this repo and you should be good to go. Thanks!
