### ISSUE TITLE
I am facing this problem please help me as soon as possible

### ISSUE THREAD

**Issue by Nitinsharmapandat** [svanas/delphereum#18]
![Screenshot (1102)](https://user-images.githubusercontent.com/67244084/146183571-93ea15ec-6e76-4205-a756-3f78c59b2529.png)

**Comment by Nitinsharmapandat** [comment]
please help me i am facing   this Error      [dcc64 Fatal Error] web3.eth.blocknative.mempool.sgc.pas(38): F2613 Unit 'sgcWebSocket' not found.

**Comment by svanas** [comment]
Unfortunately, Delphi does not come with a WebSocket implementation out-of-the-box. You will need to download and install this: https://www.esegece.com/websockets
