### ISSUE TITLE
Facing Error

### ISSUE THREAD

**Issue by TilluChauhan** [svanas/delphereum#20]
I Am Facing this error please help me as soon as possible
[dcc64 Error] web3.eth.abi.tests.pas(97): E2029 Expression expected but 'END' found
[dcc64 Fatal Error] delphereum.dpr(22): F2063 Could not compile used unit 'web3.eth.abi.tests.pas'
Failed

**Comment by svanas** [comment]
I cannot seem to reproduce this error. I have compiled the DUniX project with Delphi 11 to both the Win32 and the Win64 target.
