### ISSUE TITLE
Code example

### ISSUE THREAD

**Issue by darkducke** [svanas/delphereum#21]
Hello, I would really like to use the component, but it has no documentation or examples, how do I use SwapExactETHForTokens for pancakeswap in bscscan ?

`const
  URL = 'https://bsc-dataseed.binance.org';
begin
  web3.eth.uniswap.v2.TRouter02.Create(TWeb3.Create(URL)).SwapExactETHForTokens('', 0, 0, '', 8989898,  procedure(rcpt : ITxReceipt; err : IError)
  begin
    TThread.Synchronize(nil, procedure
    begin
      if Assigned(err) then
        MessageDlg(err.Message, TMsgDlgType.mtError, [TMsgDlgBtn.mbOK], 0)
      else
       AddMsgMemo(MLogsGeral, 'Hash: ' + rcpt.txHash);

        //ShowMessage(web3.eth.utils.fromWei(qty, web3.eth.utils.ether) + ' BNB');
    end);
  end);

end;
`

**Comment by svanas** [comment]
> it has no documentation or examples

It does have documentation and examples. Please see 11 tutorials [here](https://github.com/svanas/delphereum).

> how do I use SwapExactETHForTokens for pancakeswap

PancakeSwap is a fork of Uniswap. You can read up about SwapExactETHForTokens [here](https://docs.uniswap.org/protocol/V2/reference/smart-contracts/router-01#swapexactethfortokens).

> TWeb3.Create(URL)

If you want to connect to the BsC network, then you'll want to do this:

`TWeb3.Create(BSC, 'https://bsc-dataseed.binance.org')`
