### ISSUE TITLE
Error while transferring Token with delphi with apothem network instead of infura

### ISSUE THREAD

**Issue by khatripp** [svanas/delphereum#25]
begin
  var ERC20 := TERC20.Create(TWeb3.Create(
    Ropsten,                                            // Ropsten test net
    'https://rpc.apothem.network'),         // RPC access to Ethereum
    '0x722dd3F80BAC40c951b51BdD28Dd19d435762180');   // TST smart contract address
  try
    ERC20.Transfer(
      '24622d680bb9d6d80c4d3fb4b4818e738de64b521948b1b1c85616eeeda54ee1', // from private key
      '0xaDDcedc01C1070bCE0aF7eb853845e7811EB649C',                       // to public key
      1000000000000000,                                                   // 0.001 TST
      procedure(hash: TTxHash; err: IError)
      begin
        TThread.Synchronize(nil, procedure
        begin
          if Assigned(err) then
            MessageDlg(err.Message, TMsgDlgType.mtError, [TMsgDlgBtn.mbOK], 0)
          else
            MessageDlg(string(hash), TMsgDlgType.mtInformation, [TMsgDlgBtn.mbOK], 0);
        end);
      end);
  finally
    ERC20.Free;
  end;
end;

With Infura code is working fine but I want to transfer token with apothem network.
here, I have replaced the  Ropsten,  'https://ropsten.infura.io/v3/fc4417e777f04753b0f09069f76a67c5'),    with  Ropsten , 'https://rpc.apothem.network'),   to transfer token with apothem network. When I run and click on button It throw an error (rlp: expected input list for types.txdata)  . Can you make it work for the apothem network rather than infura ?

**Comment by svanas** [comment]
Is Apothem an EVM-compatible network? If yes, then you will need to add the chain Id to [web3.pas](https://github.com/svanas/delphereum/blob/master/web3.pas#L305)
