### ISSUE TITLE
How can I use delphieum to buy tokens

### ISSUE THREAD

**Issue by d3sw2022** [svanas/delphereum#26]
How can I use delphieum to buy tokens
(For example, use usdt to buy other tokens on the BSC chain)

**Comment by svanas** [comment]
[This article](https://svanas.medium.com/transferring-erc-20-tokens-with-delphi-bb44c05b295d) explains how to transfer ERC20 tokens, including USDT. If you want to buy tokens, you can use [this Uniswap implementation](https://github.com/svanas/delphereum/blob/master/web3.eth.uniswap.v2.pas) to do so.
