### ISSUE TITLE
master Compile Error

### ISSUE THREAD

**Issue by yingang2** [svanas/delphereum#38]
[dcc32 Fatal Error] web3.inc(4): F1054 VCL or FMX not defined, aborting. This application contains cross-framework references. Please add $(FrameworkType) as a conditional define in this project's options.

**Comment by svanas** [comment]
You should do what the error tells you to do. Add `$(FrameworkType)` as a conditional define to your project’s options and you should be good to go. See also: https://www.ideasawakened.com/post/writing-cross-framework-code-in-delphi
