### ISSUE TITLE
Should Change TChain because Can't Use Other Chain

### ISSUE THREAD

**Issue by yonghumeijj** [svanas/delphereum#40]
if want to use chain not in Tchain  

must modify web3.pas

**Comment by yonghumeijj** [comment]
> Correct, you must modify web3.pas. What chain do you want to use?

I think tchain can change to a type like record or class.what i can create outer(like i set chain id blockexplorerurl ) then pass to web3.

right?

**Comment by yonghumeijj** [comment]
> Sure we can but that is not how Delphereum was designed. You are free to open a PR.

Delphereum was designed to use some special chain?

**Comment by svanas** [comment]
Delphereum was designed with an enum for supported networks, not to use some special chain.

**Comment by yonghumeijj** [comment]
> Delphereum was designed with an enum for supported networks, not to use some special chain.

many chain is base on eth  most function can be use in this type of chain.like heco or some testnet
