### ISSUE TITLE
Create seed phrase and derive multichain wallet from it

### ISSUE THREAD

**Issue by syfonn** [svanas/delphereum#44]
It is possible to use the lib to generate a seed phrase, and deriving wallets from it ?

**Comment by svanas** [comment]
One of our contributors is working on BIP-39 and BIP32. You can expect a PR soon.

**Comment by PieterValentijn** [comment]
I am still working on it but its not that easy stuff.
I did do the Words to Seed and visa versa.

Getting the basic seed and HD key is the next step.
I’m trying to implement the BIP 44 (as that is used by majority of the wallets atm)
Bip 32 is the basis of 44 so there linked in that way.

I’m using this implementation as a reference.
https://github.com/trezor/python-mnemonic/blob/master/src/mnemonic/mnemonic.py


and we still need to implement parts of 
 def to_seed(cls, mnemonic: str, passphrase: str = "") -> bytes:
 
ands we need our own function for 
def to_hd_master_key(seed: bytes, testnet: bool = False) -> str:
where we could give PATH  as variable.

**Comment by svanas** [comment]
Status update: [we have implemented BIP-39](https://github.com/svanas/delphereum/commit/031f3a9b6252586c8a300eee21c9a91c80b7356f). Next up are: BIP-32 and BIP-44.

**Comment by svanas** [comment]
Status update: we have implemented [BIP-39](https://github.com/svanas/delphereum/commit/031f3a9b6252586c8a300eee21c9a91c80b7356f) and [BIP-32](https://github.com/svanas/delphereum/commit/80079de025ad4d5a12b1b7ef7c9326d2ff0e9c8f). Next up is: BIP-44

**Comment by svanas** [comment]
> It is possible to use the lib to generate a seed phrase, and deriving wallets from it ?

You are welcome to review https://github.com/svanas/delphereum/pull/51 if you want.

**Comment by svanas** [comment]
We have implemented [BIP-32](https://github.com/svanas/delphereum/blob/master/web3.bip32.pas) and [BIP-39](https://github.com/svanas/delphereum/blob/master/web3.bip39.pas) and [BIP-44](https://github.com/svanas/delphereum/blob/master/web3.bip44.pas)
