### ISSUE TITLE
Hi, guru,    I failed to apply ENS following the URL of  https://svanas.medium.com/delphi-and-ethereum-name-service-ens-4443cd278af7

### ISSUE THREAD

**Issue by gneowing** [svanas/delphereum#56]
Hi, guru,
   I failed to apply ENS following the URL of  https://svanas.medium.com/delphi-and-ethereum-name-service-ens-4443cd278af7
   I did connect with my MetaMask with Goerlie.
    But the name like “XXX.XXXX.test” is not supported.
    And the name like “XXX.XXXX.study” seemed OK but no “Confirm” or other possible buttons  for me to go on with applying this domain.

Detail please refer to the attached file.
[Hi guru 230511.docx](https://github.com/svanas/delphereum/files/11450658/Hi.guru.230511.docx)

**Comment by svanas** [comment]
> I did connect with my MetaMask with Goerli. But the name like “XXX.XXXX.test” is not supported.

Apparently `.test` was a Ropsten-only thing and Goerli has a deployment of the `.eth` registrar for testing purposes. 

Please try your username ending with `.eth`, for example: `gneowing.eth`

I have update the medium article accordingly.

> Detail please refer to the attached file. [Hi guru 230511.docx]

I am sorry but I cannot and will not open your attachments.

**Comment by gneowing** [comment]
Got it. Thank you.

**Comment by gneowing** [comment]
I  tried. But need money to get the ENS.
![Screenshot from 2023-05-15 09-26-58](https://github.com/svanas/delphereum/assets/11737423/3bcd3d09-7804-4a56-9404-e24a80b29282)

**Comment by svanas** [comment]
> I tried. But need money to get the ENS.

Assuming you are on the Goerli testnet, yes you need Goerli ETH to register an ENS

**Comment by gneowing** [comment]
OK. Done.
