### ISSUE TITLE
Hi, guru, while following https://svanas.medium.com/delphi-and-the-ethereum-dark-forest-5b430da3ad93, I met an  exceptiong of TsgcWSException with message 'Error Decoding Header:Switching Protocols'.

### ISSUE THREAD

**Issue by gneowing** [svanas/delphereum#58]
I git pull the latest : "Updating 7f5ac58..0399e95"
The error:
![image](https://github.com/svanas/delphereum/assets/11737423/9525fdcd-6ea1-47de-973e-9b8dd97e966e)
If pressed the button of "Continue".
![image](https://github.com/svanas/delphereum/assets/11737423/1b89855c-4dcc-46d1-8405-88dcdbd28d06)
More debugging detail.
![image](https://github.com/svanas/delphereum/assets/11737423/a16b40d9-1ced-41b3-8236-f6e056723d84)
![image](https://github.com/svanas/delphereum/assets/11737423/06f1c5ac-2ddb-488e-9ab2-b3fea6c56bf4)
While running "if not FClient.Active then repeat until FClient.Connect;", the exception triggered!
And I tried to close all the firewalls plus run the APP as administrator, still the same situation.

The code lines( I used my Alchemy API code):
procedure TFormTest.Button_Check_USDC_MemPool_Click(Sender: TObject);
var
  str_item:string;
  a_ctrl:TControl;
begin
  a_ctrl   := TControl(Sender);
  str_item := a_ctrl.Name + ' ';

  _Mempool := TSgcMempool.Subscribe(              // 1) now it is global var
    Ethereum.SetRPC(URL_MY_API_MAINNET_ALCHEMY),  // 2)
    MY_API_NATIVE_BLOCK,                          // 3) my blocknative API key: 'f8XXXXXX-XXXX-XX01-XXX4-6XXXXXXXXXX3'; 
    '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', // address to watch
    procedure(event: TJsonObject; err: IError)    // continuous events (or a blocknative error)
    begin
      var tx := web3.eth.blocknative.mempool.getTransaction(event);
      if Assigned(tx) then
        TThread.Synchronize(nil, procedure
        begin
          str_item := 'Pass! ' + str_item + tx.ToString;
          SyncLogInMemo(self.Memo_Log_,str_item,True);
        end);
    end,
    procedure(err: IError) // non-blocknative-error handler (probably a socket error)
    begin
      TThread.Synchronize(nil, procedure
      begin
        str_item := 'Fail! ' + str_item + err.Message;
        SyncLogInMemo(self.Memo_Log_,str_item,True);
      end);
    end,
    procedure
    begin
      // connection closed
      str_item := 'Done! ' + str_item;
      SyncLogInMemo(self.Memo_Log_,str_item,True);
    end);
end;

**Comment by svanas** [comment]
The server is returning the following response:

HTTP/1.1 403 Forbidden

While a normal websocket response will be:

HTTP/1.1 101 Switching Protocols

So the client is raising an exception because the server is not returning the 101 response code. For any reason, the server is returning a 403 error message to this connection, so the server doesn't allow the peer connecting to the server.

**Comment by svanas** [comment]
@gneowing What country are you from? Blocknative is telling us they "[can not operate in OFAC sanctioned countries](https://discord.com/channels/542403978693050389/542406894677917699/1111404456186228758)"

**Comment by gneowing** [comment]
@svanas Oh, I'm from China via VPN. Can BlackNative know where I am with VPN?

**Comment by svanas** [comment]
> I'm from China via VPN. Can BlackNative know where I am with VPN?

China isn't on the OFAC list and with VPN they shouldn't be able to tell. Back to the drawing board why you are receiving a 403 (not a 101) from wss://api.blocknative.com/v0

**Comment by gneowing** [comment]
So, how to ensure this wss://api.blocknative.com/v0 is OK for my env.
I tried the extension of Chrome.
![image](https://github.com/svanas/delphereum/assets/11737423/0d4422c3-461d-4c93-809d-d5b6ff2dc7d8)

**Comment by gneowing** [comment]
Thanks to chatGPT, the bug was cleared!
Just the proxy things.
function TSgcMempool.GetClient: TsgcWebSocketClient;
begin
  if not Assigned(FClient) then
  begin
    FClient := TsgcWebSocketClient.Create(nil);
    FClient.NotifyEvents := neNoSync;

    FClient.OnMessage    := DoMessage;
    FClient.OnError      := DoError;
    FClient.OnException  := DoException;
    FClient.OnDisconnect := DoDisconnect;

    FClient.HeartBeat.Enabled  := True;
    FClient.HeartBeat.Interval := 30; // seconds
    FClient.HeartBeat.Timeout  := 0;

    FClient.URL := BLOCKNATIVE_ENDPOINT;

    // TsgcWSProxy_Options.
    FClient.Proxy.Enabled := True;  
    //FClient.Proxy.ProxyType := pHTTP; 

    FClient.Proxy.Host := '127.0.0.1';
    FClient.Proxy.Port := 7890;

    //FClient.Proxy.Username := 'your_username';
    //FClient.Proxy.Password := 'your_password';

  end;

  if not FClient.Active then repeat until FClient.Connect;

  Result := FClient;
end;
![image](https://github.com/svanas/delphereum/assets/11737423/4062e50a-de71-49ac-a804-4e2af8faae40)

**Comment by svanas** [comment]
Fixed in https://github.com/svanas/delphereum/commit/58a688c3ebd28ee36a847d0b1d96cfd35a59a249
