### ISSUE TITLE
Hi, guru,  TChain.SetRPC() failed to replace the configured URL with the one needed.

### ISSUE THREAD

**Issue by gneowing** [svanas/delphereum#62]
I knew that
Ganache: TChain = (
    Id       : 1337;
    Name     : 'Ganache';
    Symbol   : 'ETH';
    TxType   : 2;
    RPC      : ('http://127.0.0.1:7545', '')
  );
But I want to replace the RPC[HTTPS], suppose the new one is <str_ip_port_ganche>.
if I use Ganache.SetRPC(str_ip_port_ganche), later an error will occur.
![image](https://github.com/svanas/delphereum/assets/11737423/1f4dc986-9f98-4303-954b-9ea7e4ddffed)

My workaround:
  // Replace RPC
  Ganache.SetRPC('');
  Result := Ganache.SetRPC(str_ip_port_ganche); 
end;

**Comment by svanas** [comment]
I am confused where the bug is. `var ganache := web3.Ganache.SetRPC('http://127.0.0.1:7545');` should "just work".
