### ISSUE TITLE
cant encode bytes32 in simple param

### ISSUE THREAD

**Issue by yonghumeijj** [svanas/delphereum#67]
func(address,bytes32)
how to use abi encode it?

SimpleContract is tuple.

**Comment by svanas** [comment]
What SimpleContract? Please be more specific.

As a general rule, you simply [include the function name and the parameters](https://github.com/svanas/delphereum/blob/master/web3.eth.ens.pas#L122) with `web3.eth.call` and be done with it. Delphereum takes care of the encoding.

Oh, and please don't file a bug when what you really have is a question -- not a bug.
