### ISSUE TITLE
I can't compile under Delphi XE 

### ISSUE THREAD

**Issue by Uefi1** [svanas/delphereum#69]
Hello, I really need web3 and I can't compile your project from Delphi XE2, I get multiple errors that can't be easily fixed help me please

**Comment by svanas** [comment]
Delphereum is not backwards-compatible with Delphi XE2. Please use Delphi 12

**Comment by Uefi1** [comment]
For some reason I cannot switch to Delphi above Xe2, so I ask you to optimize the library for compatibility

**Comment by svanas** [comment]
"Urgently"? Are you kidding me? This is an open source project. You are welcome to open a PR.

**Comment by Uefi1** [comment]
> "Urgently"? Are you kidding me? This is an open source project. You are welcome to open a PR.

Please do it from Delphi XE, I will be very grateful to you !
I managed to transfer the SimpleBaseLib4Pascal and HashLib4Pascal libraries to Delphi XE, but I could not transfer the third CryptoLib4Pascal
