### ISSUE TITLE
web3.utils    Unscale/scale  function  will lost accuracy

### ISSUE THREAD

**Issue by yonghumeijj** [svanas/delphereum#72]
like a bignumber:
big:=Biginteger('12999999999999995678');

convert use Unscale

double:=web.utils.unscale(big,18);

the right should be 
12.999999999999995678

but the result is   13.

**Comment by svanas** [comment]
This unit test passes just fine:
```delphi
const big = BigInteger('12999999999999995678');
const dbl = web3.utils.unscale(big, 18);
Assert.AreEqual(dbl, 12.999999999999995678);
```

**Comment by svanas** [comment]
Floating point variables typically have this behavior. It's caused by how they are stored in hardware.
