### ISSUE TITLE
Error on compile.

### ISSUE THREAD

**Issue by aljgardin** [svanas/delphereum#76]
Trying to run the example: [https://medium.com/@svanas/connecting-delphi-to-a-local-in-memory-blockchain-9a1512d6c5b0].
I get this error:
Code:
procedure TForm1.Button1Click(Sender: TObject);
begin
  TThread.Synchronize(nil, procedure
  begin
    if Assigned(error) then
      MessageDlg(err.Message, TMsgDlgType.mtError, [TMsgDlgBtn.mbOK], 0)
    else
      ShowMessage(web3.eth.utils.fromWei(qty, web3.eth.utils.ether) + ' ether');
  end);
end;

Errors:
[dcc64 Error] Unit1.pas(31): E2036 Variable required
[dcc64 Error] Unit1.pas(32): E2003 Undeclared identifier: 'err'
[dcc64 Error] Unit1.pas(32): E2029 'END' expected but ',' found
[dcc64 Error] Unit1.pas(35): E2029 ')' expected but 'END' found
[dcc64 Error] Unit1.pas(35): E2029 ';' expected but ')' found
[dcc64 Error] Unit1.pas(36): E2029 '.' expected but ';' found
[dcc64 Fatal Error] Project1.dpr(5): F2063 Could not compile used unit 'Unit1.pas'

I rechecked the Directory structure, looks OK:
New working with Rad Studio12,  Have been using Deplhi7 for years.
Tried a google search, no help.

Directory Structure:
![image1](https://github.com/user-attachments/assets/9bd7e49f-802f-4986-b654-857a0373948f)

[TestToLocal.zip](https://github.com/user-attachments/files/17580947/TestToLocal.zip)

**Comment by svanas** [comment]
The example in the article works but you must...

1. [include the dependences with your project's options search path](https://github.com/svanas/delphereum?tab=readme-ov-file#search-path)

2. [copy the whole example](https://gist.githubusercontent.com/svanas/e74ddc085e6282933f041c2928dc7ebd/raw/8e5cd1d76cddde8ea7ed1d57c4e895ef9793fc68/Unit1.pas) (including `web3.eth.getBalance`), not some parts of it and expect it to work.

3. add this uses clause to your form's unit:
```
uses
  // Velthuis' BigNumbers
  Velthuis.BigIntegers,
  // web3
  web3, web3.eth, web3.eth.utils;
```
I am not going to download and unzip your attachment, sorry. Too much of a security risk for me.

**Comment by aljgardin** [comment]
I checked the Search path, Was OK.

Thank you, It was the uses 
  Velthuis.BigIntegers,
  // web3
  web3, web3.eth, web3.eth.utils;

I had Web3, Web3.eth only.

Do you have the test projects in whole for download somewhere?

**Comment by svanas** [comment]
> Thank you, It was the uses

Thank you for confirming that.

> Do you have the test projects in whole for download somewhere?

That would be nice, but I really don't need more code to maintain. If someone wants to do it, I would be happy to link to them.
