### ISSUE TITLE
Subscribe is missing

### ISSUE THREAD

**Issue by cwazy2020** [svanas/delphereum#9]
The entire subscription functionality built into the web3 library is missing in Delphereum.  Do you have any guidance on how to create it ourselves?

**Comment by svanas** [comment]
It is not missing. `subscribe()` is here https://github.com/svanas/delphereum/blob/master/web3.eth.pubsub.pas

**Comment by jmonty77** [comment]
Please, could you show a simple correct usage of subscribe in delphereum?

**Comment by svanas** [comment]
> Please, could you show a simple correct usage of subscribe in delphereum?

Here is a simple example: https://github.com/svanas/PubSub

**Comment by jmonty77** [comment]
Thank you very much.
I want to capture solidity emit events, and I 've found "web3.eth.logs" unit. Does that unit same action as subscribe, but continuously pooling the server?

**Comment by svanas** [comment]
> I want to capture solidity emit events, and I 've found "web3.eth.logs" unit. Does that unit same action as subscribe, but continuously pooling the server?

[web3.eth.logs](https://github.com/svanas/delphereum/blob/master/web3.eth.logs.pas) polls the gateway inside an async task.
